### ISSUE TITLE
Request for HCS topic metadata API endpoint

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-mirror-node#6165] opened 2023-06-08 03:43 UTC
### Problem

Currently, the mirror node does not provide an API endpoint to query topic objects. The HCS topic is an object and has a lot of metadata associated to it such as admin key, submit key, etc. I think it's worth creating an API for this so the user can query to see what keys are associated with topics.

### Solution

Add `/api/v1/topics/{topic_id}`

**Comment by steven-sheehy** [comment] 2023-06-08 03:44
Duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/774

**Closed by steven-sheehy** 2023-06-08 03:44 UTC
Labels: enhancement
