### ISSUE TITLE
GCP Marketplace Mirror Node Listing

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#562] opened 2020-02-27 16:50 UTC
Placeholder Epic for GCP Mirror Node Listing.

**Comment by steven-sheehy** [comment] 2020-02-27 17:25
Duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/518 ?

**Closed** 2020-02-27 17:34 UTC
Labels: Epic
