### ISSUE TITLE
K6 perf test suite got triggered twice in staging

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#8528] opened 2024-06-11 14:18 UTC
### Description

The k6 perf test suite was triggered twice around almost the same time, one from the acceptance tests pod deletion event in `mainnet` namespace, and the other from the acceptance tests pod deletion event in `mainnet-citus`.

We need to make the `test-tigger: rest-trigger` label configurable so it's only enabled where we want. 

### Steps to reproduce

check the deployment logs and testsuite run log

### Hedera network

other

### Version

v0.107.0-rc1

### Operating system

None

**Comment by jnels124** [comment] 2024-06-17 15:46
This appears to be caused by teskube pods restarting due to scheduling issues when the new namespace came fully online. With changes made to test triggers by pr #8538 and additional changes made to the teskube pod priority classes, this issue may be resolved. Moving to backlog to let other solutions be tested.

**Comment by steven-sheehy** [comment] 2024-09-20 18:06
Closing since we now only have citus namespace in staging

**Closed by steven-sheehy** 2024-09-20 18:06 UTC
Labels: bug, test
