### ISSUE TITLE
Capture HTS token transfers through HAPI

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-mirror-node#4337] opened 2022-08-23 14:20 UTC
### Problem

HTS token transfers from HAPI are not emitting events equivalent to ERC20 transfer. Caught while testing https://github.com/hashgraph/hedera-json-rpc-relay/issues/414

### Solution

Based on the transfer return logs equivalent to the ERC20 transfer.

**Comment by steven-sheehy** [comment] 2022-08-23 14:27
Are you sure services is sending them? Mirror node stores all logs it receives.

**Comment by Kalina-Todorova** [comment] 2022-08-23 14:35
As discussed with the services team they do not send them via HAPI call and they shouldn't be sending them. 
I think the idea here is for the mirror-node to synthetically create the logs.

**Comment by steven-sheehy** [comment] 2022-09-30 18:51
I don't think mirror node should be generating data that is not sent by consensus nodes. That should come from the transaction record. @alikatamjani Can you check into this?

**Comment by shemnon** [comment] 2022-10-20 22:29
I think this was discussed on an internal call, but I don't think services should create the log events.  Either the mirror node or the JSON-RPC gateway should synthesize a log event.  It's fairly mechanical.

One issue is that it would impact the `logIndex` and `transactionIndex` fields.  Given the large scale aggression aspect of needeing to calculate block indexes it's probably better suited for calculation on the mirror node.

This also applies to ERC-721 tokens, which can generate log messages too.

**Comment by steven-sheehy** [comment] 2023-06-14 04:08
Seems to be a duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/4738 which was resolved by https://github.com/hashgraph/hedera-mirror-node/pull/5402

**Closed by steven-sheehy** 2023-06-14 04:08 UTC
Labels: enhancement
