### ISSUE TITLE
RedisEntityListenerTest.onSlowPublish fails in github CI

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#2127] opened 2021-06-16 21:40 UTC
**Detailed Description**
RedisEntityListenerTest.onSlowPublish fails in github CI.

**Actual Behavior**
Error log:

```
2021-06-16T21:33:27.5314799Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.454 s <<< FAILURE! - in com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest
2021-06-16T21:33:27.5324812Z [ERROR] com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish  Time elapsed: 0.403 s  <<< FAILURE!
2021-06-16T21:33:27.5327939Z org.opentest4j.AssertionFailedError: 
2021-06-16T21:33:27.5328578Z 
2021-06-16T21:33:27.5328963Z expected: 9
2021-06-16T21:33:27.5329358Z but was : 0
2021-06-16T21:33:27.5332683Z 	at com.hedera.mirror.importer.parser.record.entity.redis.RedisEntityListenerTest.onSlowPublish(RedisEntityListenerTest.java:105)
```

**Expected Behavior**
Test case passes.

**Environment:**

**Additional Context**

**Comment by steven-sheehy** [comment] 2021-06-16 21:44
Dupe of https://github.com/hashgraph/hedera-mirror-node/issues/1651 that you opened :)

**Comment by xin-hedera** [comment] 2021-06-16 21:45
> Dupe of #1651 that you opened :)

aha, I see

**Closed by steven-sheehy** 2021-06-16 21:44 UTC
Labels: bug
