### ISSUE TITLE
Incorrect entity keys

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#509] opened 2020-01-24 20:22 UTC
**Detailed Description**
Mainnet account 0.0.928 currently shows a different key than is returned by CryptoGetInfo.

There are likely other accounts.

This may be related to #273 as the mirror node shows no successful transactions on that account (where fk_cud_entity_id is pointing at that entity), yet it has a key set and the key is not correct.

From the change in #273, the mirror node loaded pre-OA data that wasn't available via the record streams (accounts that hadn't changed since before OA) in order to fill out missing entities in the DB. So the keys and other attributes of entities (expiry, autorenew, etc) were derived from that data. That data was incorrect and resulted in some of the entity attributes in the DB, for pre-OA accounts, being incorrect.

**Actual Behavior**

**Expected Behavior**
The key in t_entities should match the one returned by calling CryptoGetInfo on the account.

**Environment:**
mainnet (though I haven't checked against testnet)
- Version: 0.2.1

**Additional Context**
This should only impact mirror-nodes where pre-OA entity data was loaded via the accountInfo.txt script from #273

**Comment by steven-sheehy** [comment] 2021-03-05 20:41
While working on #1656, I confirmed with a newer export that we were both:
1. Missing entities entirely from before OA. 1268 of them in fact. This must be because we got an account export a little before the new mainnet bucket and it didn't include them. The aforementioned PR corrects these.
2. Some of the data in the account export was bad or out of date, causing incorrect keys to be inserted into the database in #273. This ticket is intended to correct that.

I ran the corrected export from #1656 against the `t_entities` from production and found that 4769 had mismatched keys. I've attached a CSV file that contains those entities with potentially incorrect keys. Potentially because the account's keys might have been updated after the date of the export file in which cause the value in the database would be correct.

[keys.csv.gz](https://github.com/hashgraph/hedera-mirror-node/files/6093252/keys.csv.gz)

To correct the data, I suggest we write a one-off migration that loops over the accounts in the CSV, queries HAPI `CryptoGetInfo` to get the latest data and update `t_entities` if it differs. It doesn't need to be checked in as it is specific to our Hedera mainnet network only. We can potentially do it with a bash script, hedera-cli or js-sdk and psql. Should also consider updating the other entity fields as well.

**Comment by Nana-EC** [comment] 2021-04-27 15:31
Upgrade to 0.31.0 will see the completion of this. Below are the steps to follow
1. Update the Importer `application.yaml` config to prevent parsing
```yaml
hedera:
  mirror:
    importer:
      downloader:
        balance:
          enabled: false
        record:
          enabled: false
      parser:
        balance:
          enabled: false
        record:
          enabled: false
```
2. Set importer start date to ensure the repeatable Entity migration runs. Value must be after "2019-09-14T00:00:10Z"
```yaml
importer:
  config:
    hedera:
      mirror:
        importer:
          startDate: YYYY-MM-HHTMM:SS:00Z
```
3. Start the Importer
4. Watch out for `HistoricalAccountInfoMigration` migration successfully completing
   - Expect log "Successfully updated {} accounts in {}"
   - Log of "Skipping migration since ...." signifies something wasn't configured correctly
5. Stop the importer 
6. Ensure keys.csv.gz has been downloaded and is on the importer at desired location
7. Download the [hedera-mirror-entity-info-updater](https://github.com/hashgraph/hedera-mirror-node/releases/download/v0.31.0/hedera-mirror-entity-info-updater-1.0.0.tgz) npm package. Context instructions [here](https://github.com/hashgraph/hedera-mirror-node/tree/db-entity-network-update/hedera-mirror-rest/entity-info-updater)
8. Unzip file and locate the `application.yml` under the `config` folder
9. Set the environment to point to MAINNET and configure account to be used by sdk - https://github.com/hashgraph/hedera-mirror-node/tree/db-entity-network-update/hedera-mirror-rest/entity-info-updater#environment
10. Set the DB connection details - https://github.com/hashgraph/hedera-mirror-node/tree/db-entity-network-update/hedera-mirror-rest/entity-info-updater#custom-db-endpoint-case
10. Set the package to dry-run and log level to DEBUG or TRACE as desired
11. Install (`npm install) and run the package(`npm start`)
12. Observe logs. If successful set dryRun to false and run  again

**Comment by steven-sheehy** [comment] 2021-04-27 15:34
We shouldn't modify application.yaml and in fact can't since ops will overwrite it on deploy and startup the importer via automation.

**Comment by steven-sheehy** [comment] 2022-08-31 15:56
Believe all tasks have been completed

**Closed by steven-sheehy** 2022-08-31 15:56 UTC
Labels: bug, P2, database
