### ISSUE TITLE
gRPC Consensus Service Experiencing ResourceLeak Detection

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#486] opened 2020-01-06 17:45 UTC
**Detailed Description**
During load testing on the newly developed endpoint, resource leaks were detected during topic message delivery on a subscribe to topic request

```
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]: 2020-01-05 17:50:30,119 ERROR [reactor-tcp-epoll-4] i.n.u.ResourceLeakDetector LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]: Recent access records:
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]: Created at:
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:532)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:92)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Jan 05 17:50:30 mirrornode-dev-api-1 java[21164]:         java.base/java.lang.Thread.run(Thread.java:834)
```

It's unclear that this is causing any issues in terms of the business logic. It may just be a warning of service health. As such we need to look into this to clarify.

The issue is intermittent so it's unclear what triggers it. 

**Actual Behavior**
1. Subscribe to a topic by calling gRPC endpoint.
2. View gRPC logs reporting logic
3. ResourceLeakDetector reports `LEAK: ByteBuf.release() was not called before it's garbage-collected`

**Expected Behavior**
No leak detection should occur

**Environment:**
- Java: OpenJDK 11
- Node: n/a
- OS: Mac OSX 10.14.6 & Ubuntu 16.04
- Version: 0.5.0

**Additional Context**
Logs from a recent run are attached
[jmeterGrpcLoadTestResults.log](https://github.com/hashgraph/hedera-mirror-node/files/4027167/jmeterGrpcLoadTestResults.log)

**Comment by apeksharma** [comment] 2020-01-28 03:59
Trying to reproduce, but couldn't.
Steps:
1. Started  grpc server in terminal
2. Used `ConsensusControllerTest.subscribeTopicReactive` to subscribe to a topic by calling gRPC endpoint (after changing appropriate configs)
 Saw only following logs
```
2020-01-27 18:31:00,187 INFO  [main ] c.h.m.g.MirrorGrpcApplication Starting MirrorGrpcApplication v0.5.2 on apekshits-MacBook-Pro.local with PID 96965 (/Users/appy/git/hedera-mirror-node/hedera-mirror-grpc/target/hedera-mirror-grpc-0.5.2-exec.jar started by appy in /Users/appy/git/hedera-mirror-node)
2020-01-27 18:31:00,190 INFO  [main ] c.h.m.g.MirrorGrpcApplication No active profile set, falling back to default profiles: default
2020-01-27 18:31:02,581 INFO  [main ] c.h.m.g.MirrorGrpcApplication Started MirrorGrpcApplication in 2.812 seconds (JVM running for 3.822)
2020-01-27 19:54:04,669 INFO  [grpc-default-executor-0] c.h.m.g.s.TopicMessageServiceImpl Subscribing to topic: TopicMessageFilter(endTime=null, limit=5, realmNum=0, startTime=1970-01-01T00:00:00Z, subscriberId=iiapV7tk, topicNum=0)
2020-01-27 19:54:05,807 INFO  [reactor-tcp-nio-1] c.h.m.g.s.TopicMessageServiceImpl [iiapV7tk] Topic 0.0 query complete with 3 messages in 1.129 s
2020-01-27 19:54:05,835 INFO  [reactor-tcp-nio-1] c.h.m.g.l.PollingTopicListener Starting to poll every 2000ms: TopicMessageFilter(endTime=null, limit=2, realmNum=0, startTime=2020-01-28T03:54:00.727294003Z, subscriberId=iiapV7tk, topicNum=0)
2020-01-27 19:54:07,879 INFO  [reactor-tcp-nio-10] c.h.m.g.s.TopicMessageServiceImpl [iiapV7tk] Topic 0.0 listen complete with 5 messages in 3.203 s
2020-01-27 19:55:16,455 INFO  [grpc-default-executor-1] c.h.m.g.s.TopicMessageServiceImpl Subscribing to topic: TopicMessageFilter(endTime=null, limit=5, realmNum=0, startTime=1970-01-01T00:00:00Z, subscriberId=2evKXcd9, topicNum=0)
2020-01-27 19:55:16,610 INFO  [reactor-tcp-nio-5] c.h.m.g.s.TopicMessageServiceImpl [2evKXcd9] Topic 0.0 query complete with 3 messages in 154.0 ms
2020-01-27 19:55:16,611 INFO  [reactor-tcp-nio-5] c.h.m.g.l.PollingTopicListener Starting to poll every 2000ms: TopicMessageFilter(endTime=null, limit=2, realmNum=0, startTime=2020-01-28T03:55:14.965024003Z, subscriberId=2evKXcd9, topicNum=0)
2020-01-27 19:55:18,676 INFO  [reactor-tcp-nio-4] c.h.m.g.s.TopicMessageServiceImpl [2evKXcd9] Topic 0.0 listen complete with 5 messages in 2.221 s
2020-01-27 19:57:03,948 INFO  [grpc-default-executor-2] c.h.m.g.s.TopicMessageServiceImpl Subscribing to topic: TopicMessageFilter(endTime=null, limit=5, realmNum=0, startTime=1970-01-01T00:00:00Z, subscriberId=LBGeFA96, topicNum=0)
2020-01-27 19:57:04,100 INFO  [reactor-tcp-nio-7] c.h.m.g.s.TopicMessageServiceImpl [LBGeFA96] Topic 0.0 query complete with 3 messages in 151.4 ms
2020-01-27 19:57:04,103 INFO  [reactor-tcp-nio-7] c.h.m.g.l.PollingTopicListener Starting to poll every 2000ms: TopicMessageFilter(endTime=null, limit=2, realmNum=0, startTime=2020-01-28T03:57:02.495855003Z, subscriberId=LBGeFA96, topicNum=0)
2020-01-27 19:57:06,163 INFO  [reactor-tcp-nio-6] c.h.m.g.s.TopicMessageServiceImpl [LBGeFA96] Topic 0.0 listen complete with 5 messages in 2.215 s
```

**Comment by steven-sheehy** [comment] 2020-01-28 15:40
Thanks for trying to reproduce. We've only seen it once in dev when running jmeter tests. It's more likely this error is a bug in netty/reactor/spring-boot-grpc. We've since upgrade the versions of those libraries, so maybe it's been addressed. We can probably close this soon if we don't see it again.

**Comment by Nana-EC** [comment] 2020-02-03 15:27
Just observed this in testnet based on this alert - https://hedera.pagerduty.com/incidents/PK01BY9
Error is similar

`Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         java.base/java.lang.Thread.run(Thread.java:834)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:334)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:439)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.handler.codec.LengthFieldBasedFrameDecoder.extractFrame(LengthFieldBasedFrameDecoder.java:508)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.buffer.SimpleLeakAwareByteBuf.retainedSlice(SimpleLeakAwareByteBuf.java:57)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]:         io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]: Created at:
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]: Recent access records:
Feb 03 13:22:04 mirrornode-testnet-grpc-1 java[816]: 2020-02-03 13:22:04,747 ERROR [grpc-default-executor-916] i.n.u.ResourceLeakDetector LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
`

**Comment by steven-sheehy** [comment] 2020-02-14 16:31
I believe this will be solved by this change in r2dbc:

https://github.com/r2dbc/r2dbc-postgresql/commit/6398acdd8e86a5fd0e3b7a2bcfb388f575c381b4

**Comment by mike-burrage-hedera** [comment] 2020-02-18 17:52
Still happened in 0.5.5 in dev. Trying to consistently reproduce.

```
Feb 13 17:25:10 mirrornode-dev-api-1 java[27836]:         ,L8@@@@@@@@@@@@@@@@@@0C:                                          Mirror GRPC  (v0.5.5)
Feb 13 17:29:41 mirrornode-dev-api-1 java[27836]: 2020-02-13 17:29:41,935 ERROR [parallel-1] i.n.u.ResourceLeakDetector LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
```

**Comment by mike-burrage-hedera** [comment] 2020-02-18 22:14
Unable to repro using a combination of the following variables:
- hedera-mirror-grpc 0.5.4, 0.5.5, current master
- 100-500 simultaneous subscriptions on various topics against either local or v0.5.5 running on dev instance grpc server
- maxPageSize 200-1000000
- pg_terminating backend DB processes, killing the DB mid-queries, killing the clients mid-query, pausing clients so their connections time out server side

Issue has been seen in testnet 2 times in last 7 days.

We need to log the contents of the leaked buffer (custom netty?) to get an idea of what it represents (DB connection? front-end grpc connection?) since we can't repro, or figure out a way to actually repro it consistently.

Happens infrequently-enough it's likely not worth pursuing further.

**Comment by mike-burrage-hedera** [comment] 2020-02-19 19:08
Unable to reproduce. closing.

**Closed by mike-burrage-hedera** 2020-02-19 19:08 UTC
Labels: P2, bug, grpc, hcs
