### ISSUE TITLE
REST API /api/v1/contracts/{contractId}/results/{timestamp} ignores the contractId argument

### ISSUE THREAD

**Issue by svienot** [hashgraph/hedera-mirror-node#4968] opened 2022-11-29 17:15 UTC
### Description

When calling the `/api/v1/contracts/{contractId}/results/{timestamp}` REST API, it seems that the `contractId` argument is ignored as long as it is a _valid entityId_. One would expect the call to return an error when the `timestamp` is not the consensus timestamp of a transaction related to that `contractId`.

### Steps to reproduce

`https://testnet.mirrornode.hedera.com/api/v1/contracts/1.2.3/results/1664196099.950355005`
gives the same result as:
`https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.359/results/1664196099.950355005`

### Hedera network

mainnet, testnet, previewnet

### Version

0.68.1

**Comment by steven-sheehy** [comment] 2022-11-29 17:29
Duplicate of #4380

**Closed by steven-sheehy** 2022-11-29 17:29 UTC
Labels: bug
