### ISSUE TITLE
Update Application Cache To Use Normalized URL

### ISSUE THREAD

**Issue by jnels124** [hashgraph/hedera-mirror-node#9679] opened 2024-10-29 20:28 UTC
### Problem

We recently added a redis caching layer to the rest module. This functionality should use the normalized url added by [PR](https://github.com/hashgraph/hedera-mirror-node/pull/9591)

### Solution

Update the cache key to use normalized url

**Comment by steven-sheehy** [comment] 2024-10-30 21:04
Seems to be a duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/9676

**Closed** 2024-10-30 21:05 UTC
Labels: enhancement, performance, rest
