### ISSUE TITLE
Pseudo Random Number Generator result DOES NOT show up on Mirror Node

### ISSUE THREAD

**Issue by Topachi** [hashgraph/hedera-mirror-node#5059] opened 2022-12-16 18:25 UTC
### Description

When generating a Random Number from the Hedera SDK, the random number cannot be verified through the mirror nodes as the final user is not able to counter-proof the veridicity of the number generated, even if you share the Transaction ID.
Example here: https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.47967256-1671212045-518288243

### Steps to reproduce

1) generate PseudoRandomNumber
2) execute the function
3) Check the transaction ID on mirror node

### Hedera network

testnet

### Version

latest

### Operating system

macOS

**Comment by steven-sheehy** [comment] 2022-12-16 18:32
Duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/4473

**Closed by steven-sheehy** 2022-12-16 18:32 UTC
Labels: bug
