### ISSUE TITLE
Add Transaction History for NFT Collections

### ISSUE THREAD

**Issue by jorgez19** [hashgraph/hedera-mirror-node#3720] opened 2022-05-04 19:28 UTC
### Problem

I am trying to get sales history for an NFT collection but the REST API only has a request endpoint (NFT transaction history) for transaction history of one specific NFT. Most collections have 1,000 + NFT's so I would have to send thousands of requests and parse the data to get one single update of the sales history. 

### Solution

Add a NFT Collection Transaction History endpoint with a tokenID parameter.

**Comment by steven-sheehy** [comment] 2022-11-23 19:49
Duplicate of #2551

**Closed by steven-sheehy** 2022-11-23 19:49 UTC
Labels: enhancement
