### ISSUE TITLE
Public Mirrornode bucket - wasabi

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-mirror-node#479] opened 2020-01-03 15:09 UTC
@popowycz commented on [Tue Dec 03 2019](https://github.com/hashgraph/internal/issues/43)

Current costs for hosting buckets for stream files used by mirrornodes are increasing based on pricing models by both AWS and GCP which charge by amount stored as well as by request (PUT/GET, etc). Using these mechanisms for public access is not financially sustainable. Using an alternative but byte-compatible storage provider that does not charge by request such as Wasabi could provide a reasonable alternative.

---

@steven-sheehy commented on [Tue Dec 03 2019](https://github.com/hashgraph/internal/issues/43#issuecomment-561329304)

Another alternative is [requester pays](https://github.com/hashgraph/hedera-mirror-node/issues/357) buckets. This wouldn't reduce costs for Hedera owned components like our mirror node, but would offload costs to external partners directly consuming from S3. We should ensure wasabi supports requester pays as well since we could potentially do both options to reduce costs.

**Comment by steven-sheehy** [comment] 2020-01-03 15:46
Duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/357

**Closed by steven-sheehy** 2020-01-03 15:46 UTC
