### ISSUE TITLE
Missing Endpoint: NFT Allowances by Owner

### ISSUE THREAD

**Issue by Ashe-Oro** [hashgraph/hedera-mirror-node#4349] opened 2022-08-23 21:35 UTC
### Problem

User Story: As an NFT owner, I want to quickly review all of the spending allowances that I've given to other accounts via either `approve `or `approveForAll` so that I can review who can spend what from my account. 

This endpoint currently exists for FTs: http://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.2446352/allowances/tokens

### Solution

New endpoint which returns NFT specific allowances granted for a specific account.

Should be very similar to the info provided for FTs via http://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.2446352/allowances/tokens

**Comment by steven-sheehy** [comment] 2022-08-23 22:32
Believe this is a duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/3245. Can you confirm and close if so?

**Comment by Ashe-Oro** [comment] 2022-08-24 14:15
yep, confirmed it's a duplicate. Thanks @steven-sheehy.

**Closed** 2022-08-24 14:17 UTC
Labels: duplicate, enhancement
