### ISSUE TITLE
Add Open API Specification for REST API

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#692] opened 2020-04-17 17:54 UTC
**Problem**
The REST API could benefit from a specification such as that of the [OPEN API Specification](https://swagger.io/specification/)

Benefits include
- Improved standardization
- Easier discoverability and understanding of the capabilities of our service without requiring access to source code, documentation, or through network traffic inspection.
- Expanded testing capabilities
- Expanded url validation options

**Solution**
Use [Swagger Inspector](https://swagger.io/tools/swagger-inspector/) to generate OAS or do it manually.

Additionally provide this specification to the Swagger metrics middleware handler for greater detail on metrics side.

**Alternatives**
Explore other REST API description library/framework

**Additional Context**

**Comment by steven-sheehy** [comment] 2020-04-17 19:01
Duplicate of #306

**Closed by steven-sheehy** 2020-04-17 19:01 UTC
Labels: P3, duplicate, enhancement, rest
