### ISSUE TITLE
Service unavailable when querying transactionType, for example transactionType=TOKENUPDATE

### ISSUE THREAD

**Issue by srokatonie** [hashgraph/hedera-mirror-node#3478] opened 2022-03-30 07:25 UTC
### Description

This happens every couple of days. I try to query on TESTNET:

`https://testnet.mirrornode.hedera.com/api/v1/transactions?transactionType=TOKENUPDATE&limit=1`

I get 

`{"_status":{"messages":[{"message":"Service unavailable"}]}}`

You have to wait few hours and it gets back to work. Happens when querying from several hosts (tried 3).

### Steps to reproduce

Visit `https://testnet.mirrornode.hedera.com/api/v1/transactions?transactionType=TOKENUPDATE&limit=1`

As for now, for example, (07:22 UTC) it fails to return the data.

### Additional context

![Screenshot 2022-03-30 at 09 17 49](https://user-images.githubusercontent.com/12460055/160774907-53e49124-765b-487a-90c8-c0728d7db480.png)

### Hedera network

testnet

### Version

Current available at testnet.mirrornode.hedera.com/

**Comment by steven-sheehy** [comment] 2022-03-30 14:22
Hi, thanks for your report! This is a duplicate of #2385 and #3433 which were recently fixed and will be available in the next release.

**Closed by steven-sheehy** 2022-03-30 14:22 UTC
Labels: bug, duplicate
