### ISSUE TITLE
Provide /api/v1/topics and /api/v1/topics/{topicId}

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-mirror-node#4706] opened 2022-10-22 07:28 UTC
### Problem

Unlike for other types of entity, topics are missing the following calls:
- `/api/v1/topics`
- `/api/v1/topics/{topicId}`

These calls would allow Explorer to make a better implementation of the `Topics` tab.
In particular, Explorer could expose topics which have no associated message yet.

### Solution

Add the following calls:
- `/api/v1/topics`
- `/api/v1/topics/{topicId}`
with the usual query params provided for other entities (ie pagination, sorting…)

**Comment by steven-sheehy** [comment] 2022-10-22 14:27
Duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/773

**Closed by steven-sheehy** 2022-10-22 14:27 UTC
Labels: enhancement
