### ISSUE TITLE
Contract Results with multiple hits with the same Ethereum Hash produce internal error

### ISSUE THREAD

**Issue by shemnon** [hashgraph/hedera-mirror-node#3953] opened 2022-06-15 16:29 UTC
### Description

It is possible for there to be multiple EthereumTransactions that will map to the same Ethereum Hash, resulting in a rest call that returns an internal error:

```
https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0xf0494ed39ff33a2167bf5e10ae7ea4b928774b420b31a062cab439d3dc671879

{"_status":{"messages":[{"message":"Internal error"}]}}
```

In these instances the most relevant response should be returned as though it was the only one. This would be a response that does not have a WRONG_NONCE (response number 312) status code.  In the event there are multiple of these it would likely be the earliest response, as insufficient fees should increment the nonce.

### Steps to reproduce

Submit an EthereumTransaction twice with the same ethereumTransactionData bytes.  
Attempt to query the transaction via `https://testnet.mirrornode.hedera.com/api/v1/contracts/results/<ethereumHash>`
Get a response "internal error"

### Hedera network

testnet

### Version

0.57.2 OAS3

**Comment by steven-sheehy** [comment] 2022-06-15 16:47
Duplicate of https://github.com/hashgraph/hedera-mirror-node/issues/3952

**Comment by steven-sheehy** [comment] 2022-06-20 15:09
Closing as duplicate

**Closed by steven-sheehy** 2022-06-20 15:09 UTC
Labels: bug, duplicate, limechain
